name: ToDoListApp CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Black (Code Formatter)
        run: black --check .

      - name: Run Pytest (Unit Tests)
        run: |
          pytest --disable-warnings --maxfail=1 --cov=backend --cov-report=xml

      - name: Upload Test Coverage Results
        if: always()  # Upload even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: coverage.xml  # This will be generated by pytest-cov

      - name: Upload test logs if tests fail
        if: failure()  # Only if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-results/