name: ToDoListApp CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black (Code Formatter)
        run: black --check .

      - name: Run Flake8 (Linting)
        run: flake8 --max-line-length=88

      - name: Run Pytest (Unit Tests)
        run: |
          pytest --disable-warnings --maxfail=1 --cov=backend --cov-report=xml

      - name: Upload Test Coverage Results
        if: always()  # Upload even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: coverage.xml  # This will be generated by pytest-cov

      - name: Upload test logs if tests fail
        if: failure()  # Only if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-results/